

#Spring DataSource drajver koji ?e se koristiti za komunikaciju aplikacije sa bazom
#spring.datasource.driverClassName=org.postgresql.Driver

spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/isa
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Email
spring.mail.host = smtp.gmail.com
spring.mail.username = t41659204@gmail.com
spring.mail.password = ezyx fafh hvhs ywjy
spring.mail.port=587
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=*


# Rate limiter config
resilience4j.ratelimiter.configs.default.limitForPeriod=5
resilience4j.ratelimiter.configs.default.limitRefreshPeriod=60s
resilience4j.ratelimiter.configs.default.timeoutDuration=0s

# Video upload
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=210MB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=210MB
storage.video-path=./uploads/videos
storage.thumbnail-path=./uploads/thumbnails
spring.cache.jcache.config=classpath:ehcache.xml
spring.cache.type=jcache

# ETL trending
#etl.cron=0 * * * * * SVAKI MINUT ZA TESTIRANJE
etl.cron=0 0 0 * * *

replica.id=replica-1
server.port=8080
spring.application.name=video-service-replica-1
cache.dir=C:/Users/User/Desktop/ISA/nevena i tea/isa-backend/uploads/cache-replica-1
